### ISSUE TITLE
how do you add?

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/workfront.en#27]
Issue in ./help/quicksilver/administration-and-setup/get-started-wf-administration/configure-your-firewall.md
The document states that the allow list is only for customers who are not onboarded onto admin console, and that customers who are should use a different set of instructions. But it doesn't tell you want to do. It only gives a list of domains. It does not tell you how/where to add them.

**Comment by rebeccas-workfront** [comment]
Hello

Regarding this page of the Workfront documentation (https://experienceleague.adobe.com/docs/workfront/using/administration-and-setup/get-started-administration/configure-your-firewall.html?lang=en), you wrote:

"The document states that the allow list is only for customers who are not onboarded onto admin console, and that customers who are should use a different set of instructions. But it doesn't tell you want to do. It only gives a list of domains. It does not tell you how/where to add them."

Unfortunately, we can't add details on where and how to add the domains, because every organization manages their allowlists differently. We recommend working with your IT team to configure the allowlist.

I've added a note to that effect to the article. 

Thanks for helping to improve the Workfront documentation!
