### ISSUE TITLE
Payload can't take array of scopes

### ISSUE THREAD

**Issue by cverges-medallia** [AdobeDocs/workfront.en#40]
Issue in ./help/quicksilver/workfront-fusion/apps-and-their-modules/jwt-modules.md

The JWT module itself can't support the following JWT payload option:

```{
  "scope": ["a", "b", "c"]
}```

When I attempt to add it, it looks like the array is being encoded as a string rather than being kept as an array.  I've tried several options but haven't found anything to allow me to workaround the stringification.

**Comment by rebeccas-workfront** [comment]
Hello,

Regarding this page of the Workfront documentation (https://experienceleague.adobe.com/en/docs/workfront/using/adobe-workfront-fusion/fusion-apps-and-modules/jwt-modules), you wrote:

The JWT module itself can't support the following JWT payload option: (Payload)

Because this issue is related to the product and not the documentation, I recommend submitting it as a ticket. For instructions, see https://experienceleague.adobe.com/en/docs/workfront/using/basics/tips-tricks-for-basics/contact-customer-support

Thank you!
