### ISSUE TITLE
Credentials not secured

### ISSUE THREAD

**Issue by cverges-medallia** [AdobeDocs/workfront.en#41]
Issue in ./help/quicksilver/workfront-fusion/apps-and-their-modules/jwt-modules.md

The private key being shown in clear text is super insecure.  In other places in Fusion, the private key is protected behind a Credential.  Why is that not being done for JWT, too?

**Comment by rebeccas-workfront** [comment]
Hello,

Regarding this page of the Workfront documentation (https://experienceleague.adobe.com/en/docs/workfront/using/adobe-workfront-fusion/fusion-apps-and-modules/jwt-modules), you wrote:

The private key being shown in clear text is super insecure. In other places in Fusion, the private key is protected behind a Credential. Why is that not being done for JWT, too?

Because this issue is related to the product and not the documentation, I recommend submitting it as a product request or a ticket. For instructions, see https://experienceleague.adobe.com/en/docs/workfront/using/basics/tips-tricks-for-basics/contact-customer-support

Thank you!
